CLASS LHC_INVENTORY DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.

  PRIVATE SECTION.

    METHODS SET_STATUS FOR MODIFY
      IMPORTING KEYS FOR ACTION INVENTORY~SET_STATUS RESULT RESULT.
    METHODS CHECK_PRODUCTID FOR VALIDATE ON SAVE
      IMPORTING KEYS FOR INVENTORY~CHECK_PRODUCTID.

    METHODS EMPTY_ON_SAVE FOR VALIDATE ON SAVE
      IMPORTING KEYS FOR INVENTORY~EMPTY_ON_SAVE.

    METHODS OWNER_IS_USER FOR VALIDATE ON SAVE
      IMPORTING KEYS FOR INVENTORY~OWNER_IS_USER.
*    METHODS COMBINE FOR MODIFY
*      IMPORTING KEYS FOR ACTION Inventory~COMBINE.
*
*    METHODS ISSUE_ERROR FOR MODIFY
*      IMPORTING KEYS FOR ACTION Inventory~ISSUE_ERROR.
*
*    METHODS ISSUE_INFO FOR MODIFY
*      IMPORTING KEYS FOR ACTION Inventory~ISSUE_INFO.
*
*    METHODS ISSUE_SUCCESS FOR MODIFY
*      IMPORTING KEYS FOR ACTION Inventory~ISSUE_SUCCESS.
*
*    METHODS ISSUE_WARNING FOR MODIFY
*      IMPORTING KEYS FOR ACTION Inventory~ISSUE_WARNING.


*    METHODS GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
*    IMPORTING REQUEST REQUESTED_AUTHORIZATIONS FOR Inventory RESULT RESULT.

*    METHODS IS_SET_STATUS RETURNING VALUE(BTN_ALLOWED) TYPE ABAP_BOOL.

ENDCLASS.

CLASS LHC_INVENTORY IMPLEMENTATION.

  METHOD SET_STATUS.

* Get Inventory is select
    READ ENTITIES OF ZI_FSO_INVEN_034 IN LOCAL MODE
              ENTITY INVENTORY
          ALL FIELDS WITH CORRESPONDING #( KEYS )
              RESULT DATA(LT_INVEN).
* Update data
    MODIFY ENTITIES OF ZI_FSO_INVEN_034 IN LOCAL MODE
                ENTITY INVENTORY
                UPDATE
                FIELDS ( NOTAVAILABLE )
                  WITH VALUE #( FOR LS_INVEN IN LT_INVEN ( %TKY = LS_INVEN-%TKY
                                    NOTAVAILABLE = COND #( WHEN LS_INVEN-NOTAVAILABLE = 'X' THEN ''
                                                           ELSE 'X'  ) ) )
                FAILED DATA(LS_FAIL)
              REPORTED DATA(LS_REPORT)
                MAPPED DATA(LS_RESULT).
* Get data
    READ ENTITIES OF ZI_FSO_INVEN_034 IN LOCAL MODE
              ENTITY INVENTORY
          ALL FIELDS WITH CORRESPONDING #( KEYS )
              RESULT DATA(LT_RESULT).

    RESULT = VALUE #( FOR LS_RESULT1 IN LT_RESULT ( %TKY   = LS_RESULT1-%TKY
                                                    %PARAM = LS_RESULT1 ) ).
  ENDMETHOD.

*  METHOD COMBINE.
*    DATA: LO_MSG  TYPE REF TO IF_ABAP_BEHV_MESSAGE,
*          LO_MSG2 TYPE REF TO IF_ABAP_BEHV_MESSAGE.
*    LO_MSG = NEW ZCM_INV_034( IM_TEXTID   = ZCM_INV_034=>C_MSG_SUCCESS
*                              IM_SEVERITY = IF_ABAP_BEHV_MESSAGE=>SEVERITY-SUCCESS ).
*
*    LO_MSG2 = NEW ZCM_INV_034( IM_TEXTID   = ZCM_INV_034=>C_MSG_WARNING
*                               IM_SEVERITY = IF_ABAP_BEHV_MESSAGE=>SEVERITY-INFORMATION ).
*
*    READ TABLE KEYS INTO DATA(LS_KEY) INDEX 1.
*
*    REPORTED-INVENTORY = VALUE #( ( %PKY = LS_KEY-%PKY
*                                    %MSG = LO_MSG )
*                                  ( %PKY = LS_KEY-%PKY
*                                    %MSG = LO_MSG2 ) ).
*  ENDMETHOD.
*
*  METHOD ISSUE_ERROR.
*    DATA: LO_MSG TYPE REF TO IF_ABAP_BEHV_MESSAGE.
*
*    LO_MSG = NEW ZCM_INV_034( IM_TEXTID      = ZCM_INV_034=>C_MSG_ERROR
*                              IM_SEVERITY    = IF_ABAP_BEHV_MESSAGE=>SEVERITY-ERROR
*                              IM_FIELD_OBJ_1 = '123' ).
*
*    APPEND LO_MSG TO REPORTED-%OTHER.
*  ENDMETHOD.
*
*  METHOD ISSUE_INFO.
*    DATA: LO_MSG       TYPE REF TO IF_ABAP_BEHV_MESSAGE.
*
*    LO_MSG = NEW ZCM_INV_034( IM_TEXTID   = ZCM_INV_034=>C_MSG_INFOMATION
*                              IM_SEVERITY = IF_ABAP_BEHV_MESSAGE=>SEVERITY-INFORMATION ).
*
*    APPEND LO_MSG TO REPORTED-%OTHER.
*  ENDMETHOD.
*
*  METHOD ISSUE_SUCCESS.
*    DATA: LO_MSG       TYPE REF TO IF_ABAP_BEHV_MESSAGE,
*          LS_INVENTORY LIKE LINE OF REPORTED-INVENTORY.
*    LO_MSG = NEW ZCM_INV_034( IM_TEXTID   = ZCM_INV_034=>C_MSG_SUCCESS
*                              IM_SEVERITY = IF_ABAP_BEHV_MESSAGE=>SEVERITY-SUCCESS ).
*
** cach 1
**    LOOP AT KEYS INTO DATA(LS_KEY).
**      CLEAR: LS_INVENTORY.
**      LS_INVENTORY-%PKY = LS_KEY-%PKY.
**      LS_INVENTORY-%MSG = LO_MSG.
**      APPEND LS_INVENTORY TO REPORTED-INVENTORY.
**ENDLOOP.
*
** cach 2
*    REPORTED-INVENTORY = VALUE #( FOR LS_KEY IN KEYS ( %PKY = LS_KEY-%PKY
*                                                       %MSG = LO_MSG ) ).
*
*  ENDMETHOD.
*
*  METHOD ISSUE_WARNING.
*    DATA: LO_MSG TYPE REF TO IF_ABAP_BEHV_MESSAGE.
*
*    LO_MSG = NEW ZCM_INV_034( IM_TEXTID   = ZCM_INV_034=>C_MSG_WARNING
*                              IM_SEVERITY = IF_ABAP_BEHV_MESSAGE=>SEVERITY-WARNING ).
*
*    APPEND LO_MSG TO REPORTED-%OTHER.
*  ENDMETHOD.



*  METHOD GET_GLOBAL_AUTHORIZATIONS.
*    IF REQUESTED_AUTHORIZATIONS-%UPDATE = IF_ABAP_BEHV=>MK-ON
*    OR REQUESTED_AUTHORIZATIONS-%ACTION-SET_STATUS = IF_ABAP_BEHV=>MK-ON.
*    ENDIF.
*
*  ENDMETHOD.

*  METHOD IS_SET_STATUS.
*
*  ENDMETHOD.

  METHOD CHECK_PRODUCTID.
  ENDMETHOD.

  METHOD EMPTY_ON_SAVE.
    " READ RELEVANT INSTANCE DATA
    READ ENTITIES OF ZI_FSO_INVEN_034 IN LOCAL MODE ENTITY INVENTORY
    ALL FIELDS WITH CORRESPONDING #( KEYS )
    RESULT DATA(LT_INVENTORY).

    " CHECK REMARK AND PRODUCTID INITIAL DATA
    LOOP AT LT_INVENTORY ASSIGNING FIELD-SYMBOL(<LFS_INVENTORY>).
      IF <LFS_INVENTORY>-REMARK IS INITIAL.
        APPEND VALUE #( %TKY = <LFS_INVENTORY>-%TKY ) TO FAILED-INVENTORY.

        APPEND VALUE #( %TKY = <LFS_INVENTORY>-%TKY
                        %MSG = NEW ZCM_INV_034( IM_TEXTID = ZCM_INV_034=>C_EMT_ON_SAVE
                                                IM_SEVERITY = IF_ABAP_BEHV_MESSAGE=>SEVERITY-ERROR
                                                IM_FIELDNAME = 'REMARK'
                                                )
                       %ELEMENT-REMARK = IF_ABAP_BEHV=>MK-ON
                       ) TO REPORTED-INVENTORY.

      ENDIF.
      IF <LFS_INVENTORY>-PRODUCTID IS INITIAL.
        APPEND VALUE #( %TKY = <LFS_INVENTORY>-%TKY ) TO FAILED-INVENTORY.

        APPEND VALUE #( %TKY = <LFS_INVENTORY>-%TKY
                        %MSG = NEW ZCM_INV_034( IM_TEXTID = ZCM_INV_034=>C_EMT_ON_SAVE
                                                IM_SEVERITY = IF_ABAP_BEHV_MESSAGE=>SEVERITY-ERROR
                                                IM_FIELDNAME = 'ProductId'
                                                )
                       %ELEMENT-PRODUCTID = IF_ABAP_BEHV=>MK-ON
                       ) TO REPORTED-INVENTORY.

      ENDIF.
    ENDLOOP.
  ENDMETHOD.

* Check if user is logon user
  METHOD OWNER_IS_USER.
*  Read relevant instance userr
    READ ENTITIES OF ZI_FSO_INVEN_034 IN LOCAL MODE ENTITY INVENTORY
    ALL FIELDS WITH CORRESPONDING #( KEYS )
    RESULT DATA(LT_INVENTORY).

*  Raise msg if owner is not the logon user

    LOOP AT LT_INVENTORY ASSIGNING FIELD-SYMBOL(<LFS_INVENTORY>).
      " Bỏ qua nếu CreateBy chưa có (đang CREATE mới)
      IF <LFS_INVENTORY>-CREATEBY IS INITIAL.
        CONTINUE.
      ENDIF.


      IF <LFS_INVENTORY>-CREATEBY <> SY-UNAME.
        " REJECT USER INPUT
        APPEND VALUE #( %TKY = <LFS_INVENTORY>-%TKY ) TO FAILED-INVENTORY.

        " RAISE MESSAGE
        APPEND VALUE #( %TKY = <LFS_INVENTORY>-%TKY
                        %MSG = NEW ZCM_INV_034( IM_TEXTID = ZCM_INV_034=>C_ONLY_EDIT_BY_OWNER
                                                IM_SEVERITY = IF_ABAP_BEHV_MESSAGE=>SEVERITY-ERROR
                                                IM_CREATEBY = <LFS_INVENTORY>-CREATEBY ) ) TO REPORTED-INVENTORY.


      ENDIF.
    ENDLOOP.
  ENDMETHOD.

ENDCLASS.
