CLASS ZCM_INV_034 DEFINITION
  PUBLIC
  INHERITING FROM CX_STATIC_CHECK
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    INTERFACES IF_ABAP_BEHV_MESSAGE .
    INTERFACES IF_T100_MESSAGE .
    INTERFACES IF_T100_DYN_MSG .

    CONSTANTS: BEGIN OF C_MSG_SUCCESS,
                 MSGID TYPE SYMSGID VALUE 'ZFSO_INV_034',
                 MSGNO TYPE SYMSGNO VALUE '001',
                 ATTR1 TYPE SCX_ATTRNAME VALUE '',
                 ATTR2 TYPE SCX_ATTRNAME VALUE '',
                 ATTR3 TYPE SCX_ATTRNAME VALUE '',
                 ATTR4 TYPE SCX_ATTRNAME VALUE '',
               END OF C_MSG_SUCCESS.

    CONSTANTS: BEGIN OF C_MSG_INFOMATION,
                 MSGID TYPE SYMSGID VALUE 'ZFSO_INV_034',
                 MSGNO TYPE SYMSGNO VALUE '002',
                 ATTR1 TYPE SCX_ATTRNAME VALUE '',
                 ATTR2 TYPE SCX_ATTRNAME VALUE '',
                 ATTR3 TYPE SCX_ATTRNAME VALUE '',
                 ATTR4 TYPE SCX_ATTRNAME VALUE '',
               END OF C_MSG_INFOMATION.

    CONSTANTS: BEGIN OF C_MSG_WARNING,
                 MSGID TYPE SYMSGID VALUE 'ZFSO_INV_034',
                 MSGNO TYPE SYMSGNO VALUE '003',
                 ATTR1 TYPE SCX_ATTRNAME VALUE '',
                 ATTR2 TYPE SCX_ATTRNAME VALUE '',
                 ATTR3 TYPE SCX_ATTRNAME VALUE '',
                 ATTR4 TYPE SCX_ATTRNAME VALUE '',
               END OF C_MSG_WARNING.

    CONSTANTS: BEGIN OF C_MSG_ERROR,
                 MSGID TYPE SYMSGID VALUE 'ZFSO_INV_034',
                 MSGNO TYPE SYMSGNO VALUE '004',
                 ATTR1 TYPE SCX_ATTRNAME VALUE 'FIELD_OBJ_1',
                 ATTR2 TYPE SCX_ATTRNAME VALUE '',
                 ATTR3 TYPE SCX_ATTRNAME VALUE '',
                 ATTR4 TYPE SCX_ATTRNAME VALUE '',
               END OF C_MSG_ERROR.

    CONSTANTS: BEGIN OF C_EMT_ON_SAVE,
                 MSGID TYPE SYMSGID VALUE 'ZFSO_INV_034',
                 MSGNO TYPE SYMSGNO VALUE '006',
                 ATTR1 TYPE SCX_ATTRNAME VALUE 'FIELDNAME',
                 ATTR2 TYPE SCX_ATTRNAME VALUE '',
                 ATTR3 TYPE SCX_ATTRNAME VALUE '',
                 ATTR4 TYPE SCX_ATTRNAME VALUE '',
               END OF C_EMT_ON_SAVE.

    CONSTANTS: BEGIN OF C_PRODUCT_NOT_EXIST,
                 MSGID TYPE SYMSGID VALUE 'ZFSO_INV_034',
                 MSGNO TYPE SYMSGNO VALUE '007',
                 ATTR1 TYPE SCX_ATTRNAME VALUE 'PRODUCTID',
                 ATTR2 TYPE SCX_ATTRNAME VALUE '',
                 ATTR3 TYPE SCX_ATTRNAME VALUE '',
                 ATTR4 TYPE SCX_ATTRNAME VALUE '',
               END OF C_PRODUCT_NOT_EXIST.

    CONSTANTS: BEGIN OF C_ONLY_EDIT_BY_OWNER,
                 MSGID TYPE SYMSGID VALUE 'ZFSO_INV_034',
                 MSGNO TYPE SYMSGNO VALUE '008',
                 ATTR1 TYPE SCX_ATTRNAME VALUE 'CREATEBY',
                 ATTR2 TYPE SCX_ATTRNAME VALUE '',
                 ATTR3 TYPE SCX_ATTRNAME VALUE '',
                 ATTR4 TYPE SCX_ATTRNAME VALUE '',
               END OF C_ONLY_EDIT_BY_OWNER.

    DATA: !FIELD_OBJ_1  TYPE TEXT40
         ,!PRODUCTID TYPE ZI_FSO_INVEN_034-PRODUCTID
         ,!CREATEBY  TYPE ZI_FSO_INVEN_034-CREATEBY
         ,!FIELDNAME TYPE CHAR30.

    METHODS CONSTRUCTOR
      IMPORTING
        !IM_TEXTID      LIKE IF_T100_MESSAGE=>T100KEY OPTIONAL
        !IM_SEVERITY    TYPE IF_ABAP_BEHV_MESSAGE=>T_SEVERITY OPTIONAL
        !IM_FIELD_OBJ_1 TYPE TEXT40 OPTIONAL
        !IM_PRODUCTID   TYPE ZI_FSO_INVEN_034-PRODUCTID OPTIONAL
        !IM_CREATEBY    TYPE ZI_FSO_INVEN_034-CREATEBY OPTIONAL
        !IM_FIELDNAME   TYPE CHAR30 OPTIONAL.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCM_INV_034 IMPLEMENTATION.


  METHOD CONSTRUCTOR ##ADT_SUPPRESS_GENERATION.
    SUPER->CONSTRUCTOR( ).
    CLEAR ME->TEXTID.
    IF IM_TEXTID IS INITIAL.
      IF_T100_MESSAGE~T100KEY = IF_T100_MESSAGE=>DEFAULT_TEXTID.
    ELSE.
      IF_T100_MESSAGE~T100KEY = IM_TEXTID.
    ENDIF.

    IF IM_FIELD_OBJ_1 IS NOT INITIAL.
      ME->FIELD_OBJ_1 = IM_FIELD_OBJ_1.
    ENDIF.

    IF IM_PRODUCTID IS NOT INITIAL.
      ME->PRODUCTID = IM_PRODUCTID.
    ENDIF.

    IF IM_CREATEBY IS NOT INITIAL.
      ME->CREATEBY = IM_CREATEBY.
    ENDIF.

    IF IM_FIELDNAME IS NOT INITIAL.
      ME->FIELDNAME = IM_FIELDNAME.
    ENDIF.


IF IM_SEVERITY IS NOT INITIAL.
    ME->IF_ABAP_BEHV_MESSAGE~M_SEVERITY = IM_SEVERITY.
  ELSE.
    ME->IF_ABAP_BEHV_MESSAGE~M_SEVERITY = IF_ABAP_BEHV_MESSAGE=>SEVERITY-SUCCESS.
  ENDIF.
ENDMETHOD.


ENDCLASS.
