CLASS ZCM_INV_034 DEFINITION
  PUBLIC
  INHERITING FROM CX_STATIC_CHECK
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    INTERFACES IF_ABAP_BEHV_MESSAGE .
    INTERFACES IF_T100_MESSAGE .
    INTERFACES IF_T100_DYN_MSG .

    CONSTANTS: BEGIN OF C_MSG_SUCCESS,
                 MSGID TYPE SYMSGID VALUE 'ZFSO_INV_034',
                 MSGNO TYPE SYMSGNO VALUE '001',
                 ATTR1 TYPE SCX_ATTRNAME VALUE '',
                 ATTR2 TYPE SCX_ATTRNAME VALUE '',
                 ATTR3 TYPE SCX_ATTRNAME VALUE '',
                 ATTR4 TYPE SCX_ATTRNAME VALUE '',
               END OF C_MSG_SUCCESS.

    CONSTANTS: BEGIN OF C_MSG_INFOMATION,
                 MSGID TYPE SYMSGID VALUE 'ZFSO_INV_034',
                 MSGNO TYPE SYMSGNO VALUE '002',
                 ATTR1 TYPE SCX_ATTRNAME VALUE '',
                 ATTR2 TYPE SCX_ATTRNAME VALUE '',
                 ATTR3 TYPE SCX_ATTRNAME VALUE '',
                 ATTR4 TYPE SCX_ATTRNAME VALUE '',
               END OF C_MSG_INFOMATION.

    CONSTANTS: BEGIN OF C_MSG_WARNING,
                 MSGID TYPE SYMSGID VALUE 'ZFSO_INV_034',
                 MSGNO TYPE SYMSGNO VALUE '003',
                 ATTR1 TYPE SCX_ATTRNAME VALUE '',
                 ATTR2 TYPE SCX_ATTRNAME VALUE '',
                 ATTR3 TYPE SCX_ATTRNAME VALUE '',
                 ATTR4 TYPE SCX_ATTRNAME VALUE '',
               END OF C_MSG_WARNING.

    CONSTANTS: BEGIN OF C_MSG_ERROR,
                 MSGID TYPE SYMSGID VALUE 'ZFSO_INV_034',
                 MSGNO TYPE SYMSGNO VALUE '004',
                 ATTR1 TYPE SCX_ATTRNAME VALUE 'FIELD_OBJ_1',
                 ATTR2 TYPE SCX_ATTRNAME VALUE '',
                 ATTR3 TYPE SCX_ATTRNAME VALUE '',
                 ATTR4 TYPE SCX_ATTRNAME VALUE '',
               END OF C_MSG_ERROR.

    DATA: !FIELD_OBJ_1 TYPE TEXT40.

    METHODS CONSTRUCTOR
      IMPORTING
        !IM_TEXTID      LIKE IF_T100_MESSAGE=>T100KEY OPTIONAL
        !im_SEVERITY    TYPE IF_ABAP_BEHV_MESSAGE=>T_SEVERITY OPTIONAL
        !IM_FIELD_OBJ_1 TYPE TEXT40 OPTIONAL .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCM_INV_034 IMPLEMENTATION.


  METHOD CONSTRUCTOR ##ADT_SUPPRESS_GENERATION.
    SUPER->CONSTRUCTOR( ).
    CLEAR ME->TEXTID.
    IF IM_TEXTID IS INITIAL.
      IF_T100_MESSAGE~T100KEY = IF_T100_MESSAGE=>DEFAULT_TEXTID.
    ELSE.
      IF_T100_MESSAGE~T100KEY = IM_TEXTID.
    ENDIF.

    IF IM_FIELD_OBJ_1 IS NOT INITIAL.
      ME->FIELD_OBJ_1 = IM_FIELD_OBJ_1.
    ENDIF.

    IF IM_SEVERITY IS NOT INITIAL.
      ME->IF_ABAP_BEHV_MESSAGE~M_SEVERITY = IM_SEVERITY.
    ELSE.
      ME->IF_ABAP_BEHV_MESSAGE~M_SEVERITY = IF_ABAP_BEHV_MESSAGE=>SEVERITY-SUCCESS.
    ENDIF.
  ENDMETHOD.


ENDCLASS.
